### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [javiferrer/redmine_custom_values_projects#12]
Hello. 

ive installed the plugin on an clean redmine installation, and it thows an 404 error on the project settings page:
`Started GET "/projects/joost-vehof/settings" for 172.13.1.1 at 2018-05-22 22:16:27 +0200
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"joost-vehof"}
  Current user: wvanderloop (id=6)
  Rendered projects/_form.html.erb (44.0ms)
  Rendered projects/_edit.html.erb (48.1ms)
  Rendered projects/settings/_modules.html.erb (7.0ms)
  Rendered projects/settings/_members.html.erb (13.6ms)
  Rendered projects/settings/_versions.html.erb (9.1ms)
  Rendered projects/settings/_issue_categories.html.erb (7.9ms)
  Rendered projects/settings/_wiki.html.erb (4.3ms)
  Rendered projects/settings/_repositories.html.erb (9.7ms)
  Rendered projects/settings/_boards.html.erb (4.6ms)
  Rendered projects/settings/_activities.html.erb (39.2ms)
  Rendered common/_tabs.html.erb (167.6ms)
  Rendered projects/settings.html.erb within layouts/base (169.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.2ms)
Completed 404 Not Found in 304ms (Views: 24.4ms | ActiveRecord: 41.7ms)`

`Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_custom_values_projects 0.0.1`

**Comment by javiferrer** [comment]
Fixed
