### ISSUE TITLE
Error when running Rake migrate to use the plug-in in version 4.1

### ISSUE THREAD

**Issue by pedroonrails** [javiferrer/redmine_custom_values_projects#15]
Hi, my name is Pedro, I'm an intern, and I'm responsible for Redmine and I need to use this plugin, test it locally etc., but when I'm going to run the redmine rake: plugins: migrate RAILS_ENV = development, this error appears here: 
![Captura de tela_2020-12-09_13-10-09](https://user-images.githubusercontent.com/54554062/101662433-e4aef300-3a1f-11eb-8bb3-e178e6cf7273.png)

And I really need to present the result if this plugin works or not.
someone help me please.

**Comment by javiferrer** [comment]
Fixed

**Comment by pedrofigueiredojs** [comment]
I did not understand

**Comment by javiferrer** [comment]
The bug is fixed. Try to update the project.

**Comment by pedrofigueiredojs** [comment]
Thank you very much! It worked!
