### ISSUE TITLE
Click right on issue list

### ISSUE THREAD

**Issue by rere16** [javiferrer/redmine_custom_values_projects#2]
Hi,

Thanks for your great plugin. I have an issue after installing it. When I right click on an issue (from the issue list), the menu does not display. A message error say : "Route not found possible_values_options_custom"

Redmine and plugin version 2.3

Thx for your help

**Comment by javiferrer** [comment]
Hello rere16,

I can not reproduce the error. Could you attach the full trace?

Thanks in advance.

**Comment by javiferrer** [comment]
Hello rere16,

I've found the error. Please update the code or apply this change https://github.com/javiferrer/redmine_custom_values_projects/commit/308d2024de69b2b2d3a04bd2d14063e2a2d6e6ac

Sorry for the mistake.

Regards,

Javier.

**Comment by rere16** [comment]
Thank you very much
